version: '2'
services:
  app:
    build: .
    environment:
      - NODE_ENV=production
    links:
      - db:mongodb
    ports:
      - 3000:3000

  db:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
#    volumes:
#     - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
